name: build-clash

on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: clash

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Calc short git SHA
        id: ci
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:user
#${{ steps.ci.outputs.sha_short }}